export const TOP_NAVBAR_HEIGHT = 81;
export const REVEAL_RAFFLES_CARD_HEIGHT = 272;
export const REVEAL_RAFFLES_CARD_WIDTH = 178;
export const REVEAL_RAFFLES_CARD_MUTED_COLOR = "#EAEAFF";
export const REVEAL_RAFFLES_CARD_INNER_PADDING = "11.6px";
export const REVEAL_RAFFLES_CARD_INNER_BORDER = "#FFF";
